server:
  port: 9099
  servlet:
    context-path: /apple
  tomcat:
    max-http-form-post-size: 104857600MB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.41.187:3306/apple?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: hcy
    password: HCYhcy@0901
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 42.192.41.187
    port: 9736
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      lettuce:
        shutdown-timeout: 0
    password: HCYhcy@0901
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
logging:
  level:
    root: warn
    com.inet: debug
  file:
    path: log/apple.log
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
